# fixer.io
fixer:
  url: "http://data.fixer.io/api/latest"
  api_key: "cd29943f67c047c31423cb605e9e0a19"

# Gopax
gopax:
  api_key: "1-10adb8ff-0a33-47fa-b1bc-bc52f7a15-desfffb85b425ce5f6b29fade706"
  secret_key: "66cv6ezs8UMpk9cWZmHw0LbB2tdOjBkU/yENfgYQr1pRZH4/qqJPD37ZRCgw58eCSVVm+zVCwwo7AXRUSJtCUA=="  

# Binance
binance:
  api_key: "oXVHmRfCSDDtDbB2O53fO41Eu2hVAfghsJZsSXnIsfe2IYtXipGHhbg9mnulC5R8"
  secret_key: "FCR6vghJEh9Dp6Jq9ZpBWEFXwQ9AtC3oAy5Lx1apecpFTOj0hW4Pdd5bnbwXEIKE"

# Admin Data
adminsql:
  url: "10.130.81.3" # live
  # url: "10.130.81.7" # dev
  port: 5432
  db: "admin"  
  id: "postgres"
  pw: "dkznltm!4321"

# Redis
redis:
  url: "10.130.80.4"
  port: 6379

# Slack
slack:
  url: "https://asia-northeast3-r-arques-alphasystem.cloudfunctions.net/slack_noti"

